In [1]:
import os
import torch 
import pandas as pd
from torchvision import models 
from torchinfo import summary
from pathlib import Path

from model import init_model

In [2]:
ROOT_DIR = Path(os.path.dirname(os.path.abspath('')))
TOTAL_TRAIN_SAMPLES = 50
TOTAL_TEST_SAMPLES = 10
CHANNELS = 3
BATCH_SIZE = 16
DEVICE = "cuda:1"
OCT_PRESENCE = "Usando OCT"
DUAL_IMAGE = "Dual Image"
DATA_PATH = "../data.csv"
SUMMARY_PATH = "../model_summary.csv"
HISTORY_PATH = "../history_csv"
FT_SIZE = 24
OUTPUT_TAB = 5

In [3]:
usage_mem = pd.read_csv("../usage_mem_gpu.csv")

In [4]:
models_list =  [
            "regnetx",
            "regnet16x",
            "regnet32x",
            "mobile",
            "shuffle",
            "efficient",
            "vit",
            "inception",
            "resnet",
            "regnet",
            "regnet16",
            "regnet32",
        ]

In [11]:
def get_memory(backbone: str, double_img: bool, output_tab: int):
    model, input_size = init_model(backbone, True, double_img, output_tab, FT_SIZE)
    if not double_img and not output_tab:
        res = summary(model,  device = 'cuda:1', input_size=(BATCH_SIZE,CHANNELS,input_size,input_size))
    else:
        res = summary(model, device = 'cuda:1', input_size=[(BATCH_SIZE,CHANNELS,input_size,input_size),(BATCH_SIZE,CHANNELS,input_size,input_size),(BATCH_SIZE, FT_SIZE)])
    total_bytes = res.to_megabytes(res.total_input + res.total_output_bytes + res.total_param_bytes)
    return int(total_bytes)

In [12]:
list_of_tuples = []
for model in models_list:
    res_single = get_memory(model, False, 0)
    res_single_tab = get_memory(model, False, OUTPUT_TAB)
    res_double = get_memory(model, True, 0)
    res_double_tab = get_memory(model, True, OUTPUT_TAB)
    list_of_tuples.append((model, BATCH_SIZE, 0, 0, res_single))
    list_of_tuples.append((model, BATCH_SIZE, 0, OUTPUT_TAB, res_single_tab))
    list_of_tuples.append((model, BATCH_SIZE, 1, 0, res_double))
    list_of_tuples.append((model, BATCH_SIZE, 1, OUTPUT_TAB, res_double_tab))

/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=RegNet_X_1_6GF_Weights.IMAGENET1K_V1`. You can also use `weights=RegNet_X_1_6GF_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=RegNet_X_3_2GF_Weights.IMAGENET1K_V1`. You can also use `weights=RegNet_X_3_2GF_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=MobileNet_V3_Large_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V3_Large_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ShuffleNet_V2_X1_5_Weights.IMAGENET1K_V1`. You can also use `weights=ShuffleNet_V2_X1_5_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=EfficientNet_B0_Weights.IMAGENET1K_V1`. You can also use `weights=EfficientNet_B0_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=Inception_V3_Weights.IMAGENET1K_V1`. You can also use `weights=Inception_V3_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=RegNet_Y_800MF_Weights.IMAGENET1K_V1`. You can also use `weights=RegNet_Y_800MF_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=RegNet_Y_1_6GF_Weights.IMAGENET1K_V1`. You can also use `weights=RegNet_Y_1_6GF_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/scratch/felipemarcelino/glaucoma/envs/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=RegNet_Y_3_2GF_Weights.IMAGENET1K_V1`. You can also use `weights=RegNet_Y_3_2GF_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

In [13]:
df = pd.DataFrame(list_of_tuples, columns=['backbone', 'batch_size', 'double_img','output_tab','mem_usage_torchinfo'])
df

     backbone  batch_size  double_img  output_tab  mem_usage_torchinfo
0     regnetx          16           0           0                 1353
1     regnetx          16           0           5                 1364
2     regnetx          16           1           0                 2712
3     regnetx          16           1           5                 2712
4   regnet16x          16           0           0                 2073
5   regnet16x          16           0           5                 2085
6   regnet16x          16           1           0                 4155
7   regnet16x          16           1           5                 4155
8   regnet32x          16           0           0                 2976
9   regnet32x          16           0           5                 2988
10  regnet32x          16           1           0                 5963
11  regnet32x          16           1           5                 5963
12     mobile          16           0           0                 1153
13     mobile          16           0           5                 1160
14     mobile          16           1           0                 2306
15     mobile          16           1           5                 2306
16    shuffle          16           0           0                  728
17    shuffle          16           0           5                  740
18    shuffle          16           1           0                 1466
19    shuffle          16           1           5                 1466
20  efficient          16           0           0                 1751
21  efficient          16           0           5                 1765
22  efficient          16           1           0                 3520
23  efficient          16           1           5                 3520
24        vit          16           0           0                 2947
25        vit          16           0           5                 2958
26        vit          16           1           0                 5900
27        vit          16           1           5                 5900
28  inception          16           0           0                 2410
29  inception          16           0           5                 2441
30  inception          16           1           0                 4868
31  inception          16           1           5                 4869
32     resnet          16           0           0                 2948
33     resnet          16           0           5                 2969
34     resnet          16           1           0                 5940
35     resnet          16           1           5                 5940
36     regnet          16           0           0                 1419
37     regnet          16           0           5                 1430
38     regnet          16           1           0                 2844
39     regnet          16           1           5                 2844
40   regnet16          16           0           0                 2108
41   regnet16          16           0           5                 2120
42   regnet16          16           1           0                 4225
43   regnet16          16           1           5                 4225
44   regnet32          16           0           0                 2962
45   regnet32          16           0           5                 2978
46   regnet32          16           1           0                 5949
47   regnet32          16           1           5                 5949

In [14]:
usage_mem

     backbone  batch_size  mem_usage  output_tab  double_img
0      regnet          16       1800           0           0
1     regnetx          16       1706           0           0
2    regnet16          16       2358           0           0
3   regnet16x          16       2130           0           0
4    regnet32          16       3182           0           0
5   regnet32x          16       2848           0           0
6   inception          16       3384           0           0
7      resnet          16       2700           0           0
8         vit          16       4864           0           0
9   efficient          16       2378           0           0
10     mobile          16       1676           0           0
11    shuffle          16       1326           0           0
12     regnet          16       1802           5           0
13    regnetx          16       1712           5           0
14   regnet16          16       2368           5           0
15  regnet16x          16       2148           5           0
16   regnet32          16       3194           5           0
17  regnet32x          16       2890           5           0
18  inception          16       3428           5           0
19     resnet          16       2774           5           0
20        vit          16       4866           5           0
21  efficient          16       2394           5           0
22     mobile          16       1684           5           0
23    shuffle          16       1350           5           0
24     regnet          16       2678           0           1
25    regnetx          16       2446           0           1
26   regnet16          16       3828           0           1
27  regnet16x          16       3284           0           1
28   regnet32          16       5296           0           1
29  regnet32x          16       4666           0           1
30  inception          16       5404           0           1
31     resnet          16       4756           0           1
32        vit          16       9959           0           1
33  efficient          16       3886           0           1
34     mobile          16       2456           0           1
35    shuffle          16       1896           0           1
36     regnet          16       2678           5           1
37    regnetx          16       2446           5           1
38   regnet16          16       3828           5           1
39  regnet16x          16       3284           5           1
40   regnet32          16       5296           5           1
41  regnet32x          16       4666           5           1
42  inception          16       5444           5           1
43     resnet          16       5762           5           1
44        vit          16       9959           5           1
45  efficient          16       3886           5           1
46     mobile          16       2460           5           1
47    shuffle          16       1896           5           1

In [15]:
mem_usage_general = df.merge(usage_mem)
mem_usage_general

,backbone,batch_size,double_img,output_tab,mem_usage_torchinfo,mem_usage
0,regnetx,16,0,0,1353,1706
1,regnetx,16,0,5,1364,1712
2,regnetx,16,1,0,2712,2446
3,regnetx,16,1,5,2712,2446
4,regnet16x,16,0,0,2073,2130
5,regnet16x,16,0,5,2085,2148
6,regnet16x,16,1,0,4155,3284
7,regnet16x,16,1,5,4155,3284
8,regnet32x,16,0,0,2976,2848
9,regnet32x,16,0,5,2988,2890
10,regnet32x,16,1,0,5963,4666
11,regnet32x,16,1,5,5963,4666
12,mobile,16,0,0,1153,1676
13,mobile,16,0,5,1160,1684
14,mobile,16,1,0,2306,2456
15,mobile,16,1,5,2306,2460
16,shuffle,16,0,0,728,1326
17,shuffle,16,0,5,740,1350
18,shuffle,16,1,0,1466,1896
19,shuffle,16,1,5,1466,1896
20,efficient,16,0,0,1751,2378
21,efficient,16,0,5,1765,2394
22,efficient,16,1,0,3520,3886
23,efficient,16,1,5,3520,3886
24,vit,16,0,0,2947,4864
25,vit,16,0,5,2958,4866
26,vit,16,1,0,5900,9959
27,vit,16,1,5,5900,9959
28,inception,16,0,0,2410,3384
29,inception,16,0,5,2441,3428
30,inception,16,1,0,4868,5404
31,inception,16,1,5,4869,5444
32,resnet,16,0,0,2948,2700
33,resnet,16,0,5,2969,2774
34,resnet,16,1,0,5940,4756
35,resnet,16,1,5,5940,5762
36,regnet,16,0,0,1419,1800
37,regnet,16,0,5,1430,1802
38,regnet,16,1,0,2844,2678
39,regnet,16,1,5,2844,2678
40,regnet16,16,0,0,2108,2358
41,regnet16,16,0,5,2120,2368
42,regnet16,16,1,0,4225,3828
43,regnet16,16,1,5,4225,3828
44,regnet32,16,0,0,2962,3182
45,regnet32,16,0,5,2978,3194
46,regnet32,16,1,0,5949,5296
47,regnet32,16,1,5,5949,5296

In [16]:
mem_usage_general["diff_mem"] = mem_usage_general["mem_usage"] - mem_usage_general["mem_usage_torchinfo"]

In [17]:
mem_usage_general

,backbone,batch_size,double_img,output_tab,mem_usage_torchinfo,mem_usage,diff_mem
0,regnetx,16,0,0,1353,1706,353
1,regnetx,16,0,5,1364,1712,348
2,regnetx,16,1,0,2712,2446,-266
3,regnetx,16,1,5,2712,2446,-266
4,regnet16x,16,0,0,2073,2130,57
5,regnet16x,16,0,5,2085,2148,63
6,regnet16x,16,1,0,4155,3284,-871
7,regnet16x,16,1,5,4155,3284,-871
8,regnet32x,16,0,0,2976,2848,-128
9,regnet32x,16,0,5,2988,2890,-98
10,regnet32x,16,1,0,5963,4666,-1297
11,regnet32x,16,1,5,5963,4666,-1297
12,mobile,16,0,0,1153,1676,523
13,mobile,16,0,5,1160,1684,524
14,mobile,16,1,0,2306,2456,150
15,mobile,16,1,5,2306,2460,154
16,shuffle,16,0,0,728,1326,598
17,shuffle,16,0,5,740,1350,610
18,shuffle,16,1,0,1466,1896,430
19,shuffle,16,1,5,1466,1896,430
20,efficient,16,0,0,1751,2378,627
21,efficient,16,0,5,1765,2394,629
22,efficient,16,1,0,3520,3886,366
23,efficient,16,1,5,3520,3886,366
24,vit,16,0,0,2947,4864,1917
25,vit,16,0,5,2958,4866,1908
26,vit,16,1,0,5900,9959,4059
27,vit,16,1,5,5900,9959,4059
28,inception,16,0,0,2410,3384,974
29,inception,16,0,5,2441,3428,987
30,inception,16,1,0,4868,5404,536
31,inception,16,1,5,4869,5444,575
32,resnet,16,0,0,2948,2700,-248
33,resnet,16,0,5,2969,2774,-195
34,resnet,16,1,0,5940,4756,-1184
35,resnet,16,1,5,5940,5762,-178
36,regnet,16,0,0,1419,1800,381
37,regnet,16,0,5,1430,1802,372
38,regnet,16,1,0,2844,2678,-166
39,regnet,16,1,5,2844,2678,-166
40,regnet16,16,0,0,2108,2358,250
41,regnet16,16,0,5,2120,2368,248
42,regnet16,16,1,0,4225,3828,-397
43,regnet16,16,1,5,4225,3828,-397
44,regnet32,16,0,0,2962,3182,220
45,regnet32,16,0,5,2978,3194,216
46,regnet32,16,1,0,5949,5296,-653
47,regnet32,16,1,5,5949,5296,-653

In [62]:
mem_usage_general.to_csv("../mem_diff_cu117",index=False)