In [24]:
import pandas as pd
import os
import numpy as np
from params import ROOT_DIR
from pathlib import Path

In [25]:
os.path.abspath('')

'/home/felipemarcelino/google_drive/comp_science/projects/glaucoma/notebooks'

In [26]:
labels = pd.read_excel("../labels.ods",engine="odf")

In [27]:
ROOT_DIR / Path("imgs/ZILMA PEREIRA CRUZ")

PosixPath('/home/felipemarcelino/google_drive/comp_science/projects/glaucoma/imgs/ZILMA PEREIRA CRUZ')

# EDA

In [28]:
# Remove duplicates 
labels

,Patient,date of birth,age,gender,eye (if unilateral),OCT date,G,T,TS,NS,N,NI,TI,Glaucoma
0,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,60,56,74,51,58,78,54,1
1,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,52,54,71,62,39,44,51,1
2,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,27,20,39,43,22,30,17,1
3,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,95,62,121,107,76,121,133,0
4,ADAO JOSE ANDRE 01087502,1940-11-30,"75,00",1,NaN,2015-12-15,102,52,136,153,63,145,152,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,ZENILIA DOS ANJOS,1951-06-28,"64,00",0,NaN,2015-05-29,97,64,130,122,75,118,125,0
882,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,97,72,142,92,78,111,130,0
883,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,91,65,132,88,75,103,123,0
884,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,46,41,44,62,29,54,68,1
885,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,103,64,107,188,76,118,128,0

In [29]:
len(labels[labels["Glaucoma"] == 1])/len(labels)

0.29571106094808125

In [30]:
# Almost of 30% of data has label == 1 (In other words, 30% of people have glaucoma)

In [31]:
# Get which row does not have a folder with images

In [32]:
patients_folder = os.listdir("../imgs/")

In [33]:
not_have_folder = []
id_names = labels["Patient"].values.tolist()
for patient in id_names:
    if patient in patients_folder:
        continue
    else:
        not_have_folder.append(patient)

In [34]:
not_have_folder

[]

# Join image path with labels

In [35]:
order = ["od","os"]

In [47]:
dict_data = {"Patient": [], "label": [], "photo_1": [], "photo_2": [], "eye_side": [], 
            "G": [], "T": [], "TS": [], "NS": [], "N": [], "NI": [], "TI": [], "age": []}
count = 0
for name, group in labels.groupby("Patient"):
    group.sort_index(inplace=True)
    folder_imgs =  os.listdir("../imgs/" + name)

    if len(group) == 2:
        count += 2
        
        
        if "MARCUS VINICI" in name:
            print(group)
            sys.exit(1)
            
        
        
        
        dict_data["Patient"].append(name)
        dict_data["Patient"].append(name)
        dict_data["label"].append(group.iloc[0]["Glaucoma"])
        dict_data["label"].append(group.iloc[1]["Glaucoma"])
        dict_data["eye_side"].append("right")
        dict_data["eye_side"].append("left")
        
        dict_data["G"].append(group.iloc[0]["G"])
        dict_data["T"].append(group.iloc[0]["T"])
        dict_data["TS"].append(group.iloc[0]["TS"])
        dict_data["NS"].append(group.iloc[0]["NS"])
        dict_data["N"].append(group.iloc[0]["N"])
        dict_data["NI"].append(group.iloc[0]["NI"])
        dict_data["TI"].append(group.iloc[0]["TI"])
        dict_data["age"].append(float(group.iloc[0]["age"].replace(",",".")))
        
        dict_data["G"].append(group.iloc[1]["G"])
        dict_data["T"].append(group.iloc[1]["T"])
        dict_data["TS"].append(group.iloc[1]["TS"])
        dict_data["NS"].append(group.iloc[1]["NS"])
        dict_data["N"].append(group.iloc[1]["N"])
        dict_data["NI"].append(group.iloc[1]["NI"])
        dict_data["TI"].append(group.iloc[1]["TI"])
        dict_data["age"].append(float(group.iloc[1]["age"].replace(",",".")))
       
        if "111111_Color_11MP_R_001.jpg" in list(folder_imgs):
            dict_data["photo_1"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_R_001.jpg"))
        else:
            dict_data["photo_1"].append(np.nan)
        
        if "111111_Color_11MP_R_002.jpg" in folder_imgs:
            dict_data["photo_2"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_R_002.jpg"))
        else:
            dict_data["photo_2"].append(np.nan) 
        
        if "111111_Color_11MP_L_001.jpg" in folder_imgs:
            dict_data["photo_1"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_L_001.jpg"))
        else:
            dict_data["photo_1"].append(np.nan)
        
        if "111111_Color_11MP_L_002.jpg" in folder_imgs:
            dict_data["photo_2"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_L_002.jpg"))
        else:
            dict_data["photo_2"].append(np.nan) 
    
        
    elif len(group) == 1:
        count += 1
        
        dict_data["G"].append(group.iloc[0]["G"])
        dict_data["T"].append(group.iloc[0]["T"])
        dict_data["TS"].append(group.iloc[0]["TS"])
        dict_data["NS"].append(group.iloc[0]["NS"])
        dict_data["N"].append(group.iloc[0]["N"])
        dict_data["NI"].append(group.iloc[0]["NI"])
        dict_data["TI"].append(group.iloc[0]["TI"])
        dict_data["age"].append(float(group.iloc[0]["age"].replace(",",".")))
        dict_data["Patient"].append(name)
        dict_data["label"].append(group.iloc[0]["Glaucoma"])
        
        if group.iloc[0]["eye (if unilateral)"] == "od" or group.iloc[0]["eye (if unilateral)"] is np.nan:
            dict_data["eye_side"].append("right")
           
            if "111111_Color_11MP_R_001.jpg" in list(folder_imgs):
                dict_data["photo_1"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_R_001.jpg"))
            else:
                dict_data["photo_1"].append(np.nan)

            if "111111_Color_11MP_R_002.jpg" in folder_imgs:
                dict_data["photo_2"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_R_002.jpg"))
            else:
                dict_data["photo_2"].append(np.nan) 
        
        elif group.iloc[0]["eye (if unilateral)"] == "os" :
            
            dict_data["eye_side"].append("left")
            
           
            if "111111_Color_11MP_L_001.jpg" in folder_imgs:
                dict_data["photo_1"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_L_001.jpg"))
            else:
                dict_data["photo_1"].append(np.nan)
            if "111111_Color_11MP_L_002.jpg" in folder_imgs:
                dict_data["photo_2"].append(ROOT_DIR / Path("imgs/" + name + "/111111_Color_11MP_L_002.jpg"))
            else:
                dict_data["photo_2"].append(np.nan)
        else:
            print(group.iloc[0]["eye (if unilateral)"])
            
    else:
        continue
        
        
    if len(dict_data["Patient"]) != count:
        print(count)
        print(len(dict_data["Patient"]))
        print(group)
        break

CLEMENCIA O NEVES 01038014
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
DEBORA PEREIRA 4350807
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
DIOVANNI JOSE FERREIRA
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
ELZA SOUZA DE BRITO SANTIAGO 949022
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
GERALDO M BARBARA 01043604
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
GERCINA SANTOS 2665396
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
JOAQUIM CARDOSO SANTOS 01019828
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
JOAQUIM FERMINO ALMEIDA
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
JOSE NETO FREITAS 10763753
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
LINEUZA LEONTINA MACHADO RIBEIRO 947456
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
LIONI CARDOSO PEREIRA 11130846
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARCOS MARTINS 00788298
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARCUS VINICIUS A  SANTOS 00817710
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIA ANTONIA DE JESUS 10783389
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIA APARECIDA C RODRIGUES 00462550
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIA CECILIA MENDES 10546364
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIA JOSE CARMO 00501450
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIA MACHADO ARAUJO 109603552
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIA TEREZINHA SANTOS SOUZA
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MARIO CORREA BRITTO 1027197
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
MOACIR SOALHEIRO FREITAS 1008075
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
RAIMUNDO JOSE NASCIMENTO
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
THEREZA CRISTINA ZAREMBA 11049178
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
THEREZINHA CHAVES 275780
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
VALDIVINA O SILVA 00693669
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
WILSON S LIMA 2503597
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma
edir pereira amorim 902276
/home/felipemarcelino/google_drive/comp_science/projects/glaucoma

In [37]:
print(count)

886

In [40]:
path_df = pd.DataFrame.from_dict(dict_data)

In [41]:
labels

,Patient,date of birth,age,gender,eye (if unilateral),OCT date,G,T,TS,NS,N,NI,TI,Glaucoma
0,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,60,56,74,51,58,78,54,1
1,ADALCI P SILVA 00002252,1934-05-21,"80,00",1,NaN,2014-07-04,52,54,71,62,39,44,51,1
2,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,27,20,39,43,22,30,17,1
3,ADAO A SENA 1017456,1953-07-12,"61,00",1,NaN,2014-10-21,95,62,121,107,76,121,133,0
4,ADAO JOSE ANDRE 01087502,1940-11-30,"75,00",1,NaN,2015-12-15,102,52,136,153,63,145,152,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,ZENILIA DOS ANJOS,1951-06-28,"64,00",0,NaN,2015-05-29,97,64,130,122,75,118,125,0
882,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,97,72,142,92,78,111,130,0
883,ZENILIA GOMES ALMEIDA 10105070,1944-08-20,"72,00",0,NaN,2016-04-18,91,65,132,88,75,103,123,0
884,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,46,41,44,62,29,54,68,1
885,ZILMA PEREIRA CRUZ,1955-04-19,"62,00",0,NaN,2017-02-03,103,64,107,188,76,118,128,0

In [42]:
completed_df = path_df.dropna(axis=0, subset=["photo_1","photo_2"])

In [43]:
completed_df.head()

,Patient,label,photo_1,photo_2,eye_side,G,T,TS,NS,N,NI,TI,age
0,ADALCI P SILVA 00002252,1,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,60,56,74,51,58,78,54,80.0
2,ADAO A SENA 1017456,1,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,27,20,39,43,22,30,17,61.0
3,ADAO A SENA 1017456,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,95,62,121,107,76,121,133,61.0
4,ADAO JOSE ANDRE 01087502,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,right,102,52,136,153,63,145,152,75.0
5,ADAO JOSE ANDRE 01087502,0,/home/felipemarcelino/google_drive/comp_scienc...,/home/felipemarcelino/google_drive/comp_scienc...,left,92,50,127,143,60,115,128,75.0

In [44]:
len(completed_df[completed_df["label"] == 1])/len(completed_df)

0.28100263852242746

In [45]:
completed_df.to_csv("data.csv",index=None)