In [4]:
import pandas as pd
import torch 
import os
from pathlib import Path

In [6]:
ROOT_DIR = Path(os.path.dirname(os.path.abspath('')))

In [2]:
data = pd.read_csv("../data.csv")

In [8]:
model_id = "b27c5e743b564d929b65ccb9fb74c9f3"
path = "../models/" + str(model_id) + "/"

In [9]:
train_loader = torch.load(path + "train_dataloader" + ".pth")
val_loader = torch.load(path + "val_dataloader" + ".pth")
val_loader.dataset.root_dir = ROOT_DIR
train_loader.dataset.root_dir = ROOT_DIR

In [10]:
dataset = train_loader.dataset

In [13]:
dataset.glaucoma_data.index

Int64Index([  0,   2,   3,   4,   5,   6,   8,   9,  10,  13,
            ...
            746, 747, 749, 750, 752, 753, 754, 755, 756, 757],
           dtype='int64', length=601)

In [12]:
data

,Patient,label,photo_1,photo_2,eye_side,gender,G,T,TS,NS,...,TS/NS,TS/N,TS/NI,TS/TI,NS/N,NS/NI,NS/TI,N/NI,N/TI,NI/TI
0,ADALCI P SILVA 00002252,1,imgs/ADALCI P SILVA 00002252/111111_Color_11MP...,imgs/ADALCI P SILVA 00002252/111111_Color_11MP...,right,1.0,60,56,74,51,...,1.450980,1.275862,0.948718,1.370370,0.879310,0.653846,0.944444,0.743590,1.074074,1.444444
1,ADAO A SENA 1017456,1,imgs/ADAO A SENA 1017456/111111_Color_11MP_R_0...,imgs/ADAO A SENA 1017456/111111_Color_11MP_R_0...,right,1.0,27,20,39,43,...,0.906977,1.772727,1.300000,2.294118,1.954545,1.433333,2.529412,0.733333,1.294118,1.764706
2,ADAO A SENA 1017456,0,imgs/ADAO A SENA 1017456/111111_Color_11MP_L_0...,imgs/ADAO A SENA 1017456/111111_Color_11MP_L_0...,left,1.0,95,62,121,107,...,1.130841,1.592105,1.000000,0.909774,1.407895,0.884298,0.804511,0.628099,0.571429,0.909774
3,ADAO JOSE ANDRE 01087502,0,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,right,1.0,102,52,136,153,...,0.888889,2.158730,0.937931,0.894737,2.428571,1.055172,1.006579,0.434483,0.414474,0.953947
4,ADAO JOSE ANDRE 01087502,0,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,left,1.0,92,50,127,143,...,0.888112,2.116667,1.104348,0.992188,2.383333,1.243478,1.117188,0.521739,0.468750,0.898438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,ZENILIA GOMES ALMEIDA 10105070,0,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,right,0.0,97,72,142,92,...,1.543478,1.820513,1.279279,1.092308,1.179487,0.828829,0.707692,0.702703,0.600000,0.853846
754,ZENILIA GOMES ALMEIDA 10105070,0,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,left,0.0,91,65,132,88,...,1.500000,1.760000,1.281553,1.073171,1.173333,0.854369,0.715447,0.728155,0.609756,0.837398
755,ZILMA PEREIRA CRUZ,1,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_R_00...,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_R_00...,right,0.0,46,41,44,62,...,0.709677,1.517241,0.814815,0.647059,2.137931,1.148148,0.911765,0.537037,0.426471,0.794118
756,ZILMA PEREIRA CRUZ,0,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_L_00...,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_L_00...,left,0.0,103,64,107,188,...,0.569149,1.407895,0.906780,0.835938,2.473684,1.593220,1.468750,0.644068,0.593750,0.921875
757,edir pereira amorim 902276,1,imgs/edir pereira amorim 902276/111111_Color_1...,imgs/edir pereira amorim 902276/111111_Color_1...,left,0.0,62,50,68,81,...,0.839506,1.133333,0.764045,1.658537,1.350000,0.910112,1.975610,0.674157,1.463415,2.170732

In [14]:
data.iloc[dataset.glaucoma_data.index]

,Patient,label,photo_1,photo_2,eye_side,gender,G,T,TS,NS,...,TS/NS,TS/N,TS/NI,TS/TI,NS/N,NS/NI,NS/TI,N/NI,N/TI,NI/TI
0,ADALCI P SILVA 00002252,1,imgs/ADALCI P SILVA 00002252/111111_Color_11MP...,imgs/ADALCI P SILVA 00002252/111111_Color_11MP...,right,1.0,60,56,74,51,...,1.450980,1.275862,0.948718,1.370370,0.879310,0.653846,0.944444,0.743590,1.074074,1.444444
2,ADAO A SENA 1017456,0,imgs/ADAO A SENA 1017456/111111_Color_11MP_L_0...,imgs/ADAO A SENA 1017456/111111_Color_11MP_L_0...,left,1.0,95,62,121,107,...,1.130841,1.592105,1.000000,0.909774,1.407895,0.884298,0.804511,0.628099,0.571429,0.909774
3,ADAO JOSE ANDRE 01087502,0,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,right,1.0,102,52,136,153,...,0.888889,2.158730,0.937931,0.894737,2.428571,1.055172,1.006579,0.434483,0.414474,0.953947
4,ADAO JOSE ANDRE 01087502,0,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,imgs/ADAO JOSE ANDRE 01087502/111111_Color_11M...,left,1.0,92,50,127,143,...,0.888112,2.116667,1.104348,0.992188,2.383333,1.243478,1.117188,0.521739,0.468750,0.898438
5,ADAO MOREIRA SOUZA 01025453,0,imgs/ADAO MOREIRA SOUZA 01025453/111111_Color_...,imgs/ADAO MOREIRA SOUZA 01025453/111111_Color_...,right,1.0,107,70,154,118,...,1.305085,1.604167,1.157895,1.252033,1.229167,0.887218,0.959350,0.721805,0.780488,1.081301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,ZENILIA GOMES ALMEIDA 10105070,0,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,right,0.0,97,72,142,92,...,1.543478,1.820513,1.279279,1.092308,1.179487,0.828829,0.707692,0.702703,0.600000,0.853846
754,ZENILIA GOMES ALMEIDA 10105070,0,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,imgs/ZENILIA GOMES ALMEIDA 10105070/111111_Col...,left,0.0,91,65,132,88,...,1.500000,1.760000,1.281553,1.073171,1.173333,0.854369,0.715447,0.728155,0.609756,0.837398
755,ZILMA PEREIRA CRUZ,1,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_R_00...,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_R_00...,right,0.0,46,41,44,62,...,0.709677,1.517241,0.814815,0.647059,2.137931,1.148148,0.911765,0.537037,0.426471,0.794118
756,ZILMA PEREIRA CRUZ,0,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_L_00...,imgs/ZILMA PEREIRA CRUZ/111111_Color_11MP_L_00...,left,0.0,103,64,107,188,...,0.569149,1.407895,0.906780,0.835938,2.473684,1.593220,1.468750,0.644068,0.593750,0.921875
757,edir pereira amorim 902276,1,imgs/edir pereira amorim 902276/111111_Color_1...,imgs/edir pereira amorim 902276/111111_Color_1...,left,0.0,62,50,68,81,...,0.839506,1.133333,0.764045,1.658537,1.350000,0.910112,1.975610,0.674157,1.463415,2.170732